#! /bin/bash

xcode-select --install

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
# Add path for home-brew

# stuff java/scala/etc. probably wont be doing this again
# term_apps=(
# maven
# tmux
# node
# )

# terminal apps
term_apps=(
wget
git
vim
neovim
httpie
fzf
ripgrep
trash
entr
rye
)
brew install ${term_apps[@]}

git clone --separate-git-dir=$HOME/.dotfiles https://github.com/olambo/.dotfiles.git tmpdotfiles
rsync --recursive --verbose --exclude '.git' tmpdotfiles/ $HOME/
rm -r tmpdotfiles

# softwareupdate --install-rosetta
#   
# curl -fLo cs https://git.io/coursier-cli-"$(uname | tr LD ld)"
# chmod +x cs
# ./cs install cs
# ./cs setup
# rm cs
Open new terminal window

#scala
#brew tap AdoptOpenJDK/openjdk
#brew cask install adoptopenjdk8

cask_apps=(
keyboard-maestro
nordvpn
enpass
)
# macos cask apps
cask_apps=(
karabiner-elements
hammerspoon
alfred
betterzip
vlc
iterm2
visual-studio-code
)
brew install --appdir="/Applications" ${cask_apps[@]}

# Remove brew cruft
brew cleanup

git clone https://github.com/softmoth/zsh-vim-mode ~/.config/zsh-vim-mode

curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# brew install --cask intellij-idea-ce
brew install cormacrelf/tap/dark-notify

dot remote set-url origin git@github.com:olambo/.dotfiles.git

# set up colors for iterm2
# iterm2/Profiles/colors - install PhonixColorDark(Light)
# iterm2/General/preferences/ - Load preferences from /Users/owl/.config/iterm
#
# stuff to do
# Enpass - icloud sync login
# Alfred - key shortcut
# karabiner-elements - start, add permissions
# Vim - PlugInstall
# Email - add account

echo "install is done!"
