# BORGMATIC CONFIGURATION FILE
# 
# To restore on new machine:
# 1. Set up SSH key authentication with borgbase.com (add your public key to borgbase account)
# 2. Save this file as ~/.config/borgmatic/config.yaml  
# 3. Save Enpass / Borg Backup Keys / encryption_passphrase to ~/.config/borgmatic/.borg-passphrase-file
# 4. Import Borg key from Enpass "Borg Key" field:
#    Save the key text to a file, then: borg key import ssh://e526z4nk@e526z4nk.repo.borgbase.com/./repo /path/to/key-file
#    Or paste interactively: borg key import ssh://e526z4nk@e526z4nk.repo.borgbase.com/./repo
# 5. Test with: borgmatic config validate && borgmatic list
#
source_directories:
    - ~/Documents
    - ~/Library/Containers/in.sinew.Enpass-Desktop/Data/Documents

exclude_patterns:
    - '*.DS_Store'
    - '*.localized'

repositories:
    - path: ssh://e526z4nk@e526z4nk.repo.borgbase.com/./repo
      label: "macbak"

compression: auto,zstd
archive_name_format: '{hostname}-{now:%Y-%m-%d-%H%M%S}'
retries: 3
retry_wait: 10

keep_daily: 7     # Keep a week
keep_weekly: 4
keep_monthly: 12

checks:
    - name: repository
    - name: archives

# handle the passphrase
encryption_passcommand: "cat ${HOME}/.config/borgmatic/.borg-passphrase-file"

# Commands using the new (verbose) syntax
commands:
    - before: action
      when: [create]
      run:
          - echo "Starting backup..."
    - after: action
      when: [create]
      states: [finish]
      run:
          - echo "Backup completed successfully!"
